spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600
  refresh-expiration: 2592000

apple:
  jwks-url: https://appleid.apple.com/auth/keys
  client-id: ${APPLE_CLIENT_ID}

kakao:
  api-base-url: https://kapi.kakao.com

google:
  jwks-url: https://www.googleapis.com/oauth2/v3/certs
  client-id: ${GOOGLE_CLIENT_ID}

line:
  api-base-url: https://api.line.me

instagram:
  api-base-url: https://graph.instagram.com

facebook:
  jwks-url: https://www.facebook.com/.well-known/oauth/openid/jwks/
  client-id: ${FACEBOOK_CLIENT_ID:990121817063522}

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN
    org.springframework.web.filter: WARN
