-- ════════════════════════════════════════════════════════════════════
-- V79 — 회관 기록(도서관) 통계 (GROMO-1769 · island-records LLD §3·§4)
-- ════════════════════════════════════════════════════════════════════
-- 번호 V78 은 상점 PR 이 쓰도록 비워 둔다. 날짜 축은 UTC 다(2026-09-19 결정 RC-축, Q-6 과 같은 축).
-- 기존 daily_screen_time_stats(KST 라벨·user/date 유일)는 건드리지 않고 읽지도 않는다(LLD §5 legacy 공존).

-- 1) 기기별 스크린타임 관측 — (사용자, 기기, UTC 날짜, 관측 시각) 하나가 불변 행 하나다(RC-P07·P08).
--    「기기·날짜의 최신 선택」은 measured_at 최댓값이라 포인터 행을 따로 두지 않는다 — 관측이 불변이고
--    같은 사용자의 PUT 은 users 행 배타 락으로 직렬화되므로 max 가 곧 포인터다. 병합 projection 은 저장하지
--    않고 조회 때 계산한다(복수 기기 병합 RC-D02 는 보류 — 저장 축만 확정, 2026-09-18 결정 D7).
--    device_id 는 서버가 서명한 로그인 세션 id 와 같아야 한다(2026-09-19 결정 RC-기기) — 임의 기기 등록 없음.
CREATE TABLE screen_time_observations (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            uuid        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    device_id          uuid        NOT NULL,
    measured_date      date        NOT NULL,
    measured_at        timestamptz NOT NULL,
    minutes            integer,
    measurement_status varchar(12) NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_screen_time_observation UNIQUE (user_id, device_id, measured_date, measured_at),
    CONSTRAINT screen_time_observations_status_check
        CHECK (measurement_status IN ('authorized', 'denied', 'unavailable', 'pending')),
    -- 측정된 0 만 0 이다 — authorized 가 아니면 숫자가 없다(RC-P06).
    CONSTRAINT screen_time_observations_minutes_check
        CHECK ((measurement_status = 'authorized') = (minutes IS NOT NULL)
            AND (minutes IS NULL OR minutes BETWEEN 0 AND 1440))
);

CREATE INDEX idx_screen_time_observations_user_date ON screen_time_observations (user_id, measured_date);

-- 2) 집중 통계 조회 스냅샷 — scope=me 기록 페이지를 같은 시점의 표로 이어 준다(LLD §3). 요청자 본인의 기록만
--    담는다(scope=island 는 주민 수가 페이지보다 작아 커서를 발급하지 않는다) — 그래서 타인의 개인정보 사본이
--    생기지 않고, 탈퇴는 이 행을 같은 TX 에서 지운다. 수명 15분(커서 만료와 같다).
CREATE TABLE focus_statistics_snapshots (
    id         uuid        PRIMARY KEY,
    user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    payload    text        NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_focus_statistics_snapshots_user ON focus_statistics_snapshots (user_id);
