/**
 * GROMO 2.0 디자인 토큰.
 *
 * 원본 UI kit의 primitive 값을 앱에서 쓸 수 있는 숫자/색상 값으로 옮기고,
 * primitive -> semantic -> component 순서로만 참조한다.
 */
export const primitiveTokens = {
  color: {
    white: '#FFFFFF',
    black: '#000000',
    pink: '#FFA6BC',
    pinkHover: '#FFB8CA',
    sky: '#ADE1F8',
    butter: '#FFE08A',
    cream: '#FFF7EB',
    paper: '#FFFDFA',
    brown: '#8B6956',
    ink: '#493B39',
    mutedBrown: '#796256',
    selectedPink: '#FFE2EA',
    subtlePink: '#FFF0F3',
    danger: '#994C3E',
    dangerStrong: '#B84A32',
    dangerInk: '#7A2E1E',
    dangerSurface: '#F4C0C0',
    dangerSoft: '#F7E9E3',
    success: '#3FB6A0',
    letter: '#FFF0CF',
    letterBorder: '#E7CF9A',
    controlIdle: '#D9C6B8',
    progressTrack: '#EADFD2',
    graphLine: '#5FB6E3',
    gramophonePanel: '#9C6440',
    gramophoneWood: '#B87848',
    gramophoneWoodLight: '#D19B61',
    gramophoneWoodDark: '#65462F',
    gramophoneRecord: '#342F2B',
    gramophoneRecordGroove: '#24211F',
    gramophoneText: '#FFF7E7',
    gramophoneTextMuted: '#FFFFFF',
    gramophoneSignText: '#211E1B',
    gramophoneShadow: '#3B291C',
    nightCanvas: '#1D2521',
    nightSurface: '#26302A',
    nightSoft: '#313C33',
    nightField: '#212B25',
    nightInk: '#F0F0E4',
    nightMuted: '#B6C2B0',
    nightLine: '#424E43',
    nightOutline: '#81917E',
    nightPrimary: '#BED3B4',
    nightPrimaryHover: '#D0E1C7',
    nightPrimaryInk: '#23382A',
    nightSelected: '#354837',
    nightAccent: '#393D2E',
    nightDanger: '#F1AC98',
    nightDangerSoft: '#493B33',
    nightLetterInk: '#E8DDBB',
  },
  space: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
    12: 48,
    16: 64,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 20,
    xl: 26,
    display: 32,
  },
  fontWeight: {
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extraBold: '800',
  },
  radius: {
    control: 14,
    card: 20,
    preview: 22,
    sheet: 26,
    full: 999,
  },
  stroke: {
    subtle: 1,
    default: 1.5,
    strong: 2,
  },
  size: {
    tapMin: 44,
  },
  duration: {
    fast: 140,
    normal: 220,
  },
} as const;

const { color, space, fontSize, fontWeight, radius, stroke, size, duration } = primitiveTokens;

export const semanticTokens = {
  color: {
    canvas: color.cream,
    surface: color.paper,
    field: color.paper,
    text: color.ink,
    textMuted: color.mutedBrown,
    outline: color.brown,
    primary: color.pink,
    primaryHover: color.pinkHover,
    onPrimary: color.ink,
    secondary: color.sky,
    accent: color.butter,
    selected: color.selectedPink,
    subtle: color.subtlePink,
    danger: color.danger,
    dangerSoft: color.dangerSoft,
    letter: color.letter,
    divider: `${color.brown}33`,
    overlay: `${color.ink}66`,
    overlaySheet: `${color.ink}40`,
  },
  nightColor: {
    canvas: color.nightCanvas,
    surface: color.nightSurface,
    field: color.nightField,
    text: color.nightInk,
    textMuted: color.nightMuted,
    outline: color.nightOutline,
    primary: color.nightPrimary,
    primaryHover: color.nightPrimaryHover,
    onPrimary: color.nightPrimaryInk,
    secondary: color.nightSoft,
    accent: color.nightAccent,
    selected: color.nightSelected,
    danger: color.nightDanger,
    dangerSoft: color.nightDangerSoft,
    letter: color.nightAccent,
    letterInk: color.nightLetterInk,
  },
  spacing: {
    control: space[3],
    component: space[4],
    section: space[6],
    page: space[5],
  },
  typography: {
    caption: fontSize.xs,
    label: fontSize.sm,
    body: fontSize.md,
    title: fontSize.lg,
    heading: fontSize.xl,
    display: fontSize.display,
    regular: fontWeight.regular,
    medium: fontWeight.medium,
    semibold: fontWeight.semibold,
    bold: fontWeight.bold,
    extraBold: fontWeight.extraBold,
  },
  radius: {
    control: radius.control,
    card: radius.card,
    preview: radius.preview,
    sheet: radius.sheet,
    full: radius.full,
  },
  stroke,
  size,
  duration,
} as const;

export const componentTokens = {
  diary: {
    referenceWidth: 402,
    maxWidth: 560,
    headerInset: space[6],
    bookTop: 85,
    contentTop: 174,
    contentLeftRatio: 54 / 402,
    contentRightRatio: 34 / 402,
    contentBottom: 78,
    headerTop: 53,
    headerHeight: size.tapMin,
    periodGap: space[4],
    contentGap: space[4],
    chartHeight: 108,
    timetableRowHeight: space[5],
    timetableGap: space[1],
    tableRowHeight: 50,
    avatarSize: space[12],
    residentMinHeight: 104,
    pressedOpacity: 0.7,
    unavailableOpacity: 0.35,
  },
  button: {
    background: semanticTokens.color.primary,
    backgroundHover: semanticTokens.color.primaryHover,
    foreground: semanticTokens.color.onPrimary,
    secondaryBackground: semanticTokens.color.surface,
    destructiveBackground: color.dangerSurface,
    destructiveBorder: color.dangerStrong,
    destructiveForeground: color.dangerInk,
    glassBackground: `${color.paper}B8`,
    height: 52,
    heightSmall: 38,
    heightGhost: semanticTokens.size.tapMin,
    radius: semanticTokens.radius.full,
    borderWidth: semanticTokens.stroke.strong,
    disabledOpacity: 0.45,
  },
  card: {
    background: semanticTokens.color.surface,
    foreground: semanticTokens.color.text,
    border: semanticTokens.color.outline,
    borderWidth: semanticTokens.stroke.default,
    radius: semanticTokens.radius.card,
    padding: semanticTokens.spacing.page,
    gap: semanticTokens.spacing.control,
  },
  input: {
    background: semanticTokens.color.field,
    foreground: semanticTokens.color.text,
    placeholder: semanticTokens.color.textMuted,
    border: semanticTokens.color.outline,
    borderWidth: semanticTokens.stroke.default,
    radius: semanticTokens.radius.control,
    minHeight: 48,
  },
  badge: {
    default: {
      background: semanticTokens.color.accent,
      foreground: semanticTokens.color.text,
      border: semanticTokens.color.outline,
    },
    soft: {
      background: semanticTokens.color.surface,
      foreground: semanticTokens.color.textMuted,
      border: color.controlIdle,
    },
    borderWidth: semanticTokens.stroke.default,
    radius: semanticTokens.radius.full,
  },
  shopStatusLabel: {
    minHeight: primitiveTokens.space[6],
    horizontalPadding: semanticTokens.spacing.control,
    fontSize: semanticTokens.typography.label,
    borderWidth: semanticTokens.stroke.default,
    radius: semanticTokens.radius.full,
  },
  progress: {
    track: color.progressTrack,
    fill: semanticTokens.color.primary,
    height: 8,
  },
  homeQuestIndicator: {
    width: 200,
    noteWidth: 190,
    noteMinHeight: 86,
    touchTrailingSpace: space[3],
    contentPaddingTop: space[3],
    contentPaddingBottom: space[2],
    contentPaddingLeft: space[4],
    contentPaddingRight: space[12],
    largeTextContentPaddingRight: space[16],
    largeTextThreshold: 1.3,
    backWidth: 184,
    backFarInsetLeft: 10,
    backFarInsetTop: space[3],
    backFarInsetBottom: space[2],
    backNearInsetLeft: 5,
    backNearInsetTop: 6,
    backNearInsetBottom: 14,
    badgeMinSize: 28,
    tapeWidth: 46,
    hudGap: space[1],
    shadow: `0px ${space[1]}px 0px ${semanticTokens.color.outline}`,
  },
  gramophone: {
    panelBackground: color.gramophonePanel,
    signStart: color.gramophoneWood,
    signCenter: color.gramophoneWoodLight,
    signEnd: color.gramophoneWood,
    woodBorder: color.gramophoneWoodDark,
    recordBackground: color.gramophoneRecord,
    recordGroove: color.gramophoneRecordGroove,
    foreground: color.gramophoneText,
    foregroundMuted: color.gramophoneTextMuted,
    signForeground: color.gramophoneSignText,
    rowForeground: semanticTokens.color.text,
    panelShadow: `0px 7px 14px ${color.gramophoneShadow}66`,
    signShadow: `0px 3px 0px ${color.gramophoneWoodDark}`,
    touchMin: semanticTokens.size.tapMin,
    panelWidth: 366,
    compactPanelWidth: 500,
    panelHeight: 226,
    compactPanelHeight: 210,
    contentHeight: 194,
    compactContentHeight: 174,
    recordSize: 112,
    controlWidth: 60,
    rowMinHeight: semanticTokens.size.tapMin,
    largeTextThreshold: 1.3,
  },
  divider: {
    color: semanticTokens.color.divider,
    width: semanticTokens.stroke.subtle,
  },
  overlay: {
    background: semanticTokens.color.overlay,
    sheetBackground: semanticTokens.color.overlaySheet,
  },
} as const;

/** 기존 화면의 C.* 사용처를 깨지 않고 semantic token으로 연결하는 호환 별칭. */
export const C = {
  pink: semanticTokens.color.primary,
  sky: semanticTokens.color.secondary,
  butter: semanticTokens.color.accent,
  cream: semanticTokens.color.canvas,
  paper: semanticTokens.color.surface,
  brown: semanticTokens.color.outline,
  ink: semanticTokens.color.text,
  muted: semanticTokens.color.textMuted,
  soft: semanticTokens.color.selected,
  danger: semanticTokens.color.danger,
} as const;
