-- 현행 19종 사건 + 렌더 전용 묶음 4종. 생성 후 변경은 Console 등록부가 소유한다.
-- 발송 게이트와 잡은 별도 활성화하므로 이 마이그레이션 자체는 FCM 을 열지 않는다.
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('LEAGUE_WEEKLY_RESULT',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_WEEKLY_RESULT.ko','LEAGUE_WEEKLY_RESULT','ko','{result, select, PROMOTED {🎉 우리 승격했어 !} RELEGATED {저번 주 리그가 종료되었어요!} other {새 리그 시작!}}','{result, select, PROMOTED {이번 주 몰입으로 {previousTierLevel, select, 1 {뽀시래기} 2 {예열 모드} 3 {초집중 모드} 4 {갓생러} 5 {집중 정복자} other {뽀시래기}} 리그에서 {newTierLevel, select, 1 {뽀시래기} 2 {예열 모드} 3 {초집중 모드} 4 {갓생러} 5 {집중 정복자} other {뽀시래기}} 리그에 올라갔어. 새 순위 보러 올래?} RELEGATED {저번 주 {previousTierLevel, select, 1 {뽀시래기} 2 {예열 모드} 3 {초집중 모드} 4 {갓생러} 5 {집중 정복자} other {뽀시래기}} 리그에서 이번 주 {newTierLevel, select, 1 {뽀시래기} 2 {예열 모드} 3 {초집중 모드} 4 {갓생러} 5 {집중 정복자} other {뽀시래기}} 리그로 이동했어요. 조금 더 힘내봐요!} other {이번 주 리그가 새로 시작됐어. 오늘 목표는? 지금 바로 몰입 시작하자!}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_WEEKLY_RESULT.en','LEAGUE_WEEKLY_RESULT','en','{result, select, PROMOTED {🎉 We moved up!} RELEGATED {Last week’s league is over!} other {A new league begins!}}','{result, select, PROMOTED {Your focus took you from {previousTierLevel, select, 1 {Rookie} 2 {Warm-up} 3 {Deep Focus} 4 {Life Master} 5 {Focus Champion} other {Rookie}} to {newTierLevel, select, 1 {Rookie} 2 {Warm-up} 3 {Deep Focus} 4 {Life Master} 5 {Focus Champion} other {Rookie}}. Check your new rank!} RELEGATED {You moved from {previousTierLevel, select, 1 {Rookie} 2 {Warm-up} 3 {Deep Focus} 4 {Life Master} 5 {Focus Champion} other {Rookie}} to {newTierLevel, select, 1 {Rookie} 2 {Warm-up} 3 {Deep Focus} 4 {Life Master} 5 {Focus Champion} other {Rookie}}. Let’s keep going!} other {A new week, a new league. Start focusing on your goal!}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_WEEKLY_RESULT.ja','LEAGUE_WEEKLY_RESULT','ja','{result, select, PROMOTED {🎉 昇格したよ！} RELEGATED {先週のリーグが終了しました！} other {新しいリーグがスタート！}}','{result, select, PROMOTED {今週の集中で{previousTierLevel, select, 1 {ひよっこ} 2 {ウォームアップ} 3 {超集中} 4 {充実ライフ} 5 {集中の達人} other {ひよっこ}}から{newTierLevel, select, 1 {ひよっこ} 2 {ウォームアップ} 3 {超集中} 4 {充実ライフ} 5 {集中の達人} other {ひよっこ}}へ昇格したよ。新しい順位を見てみよう！} RELEGATED {{previousTierLevel, select, 1 {ひよっこ} 2 {ウォームアップ} 3 {超集中} 4 {充実ライフ} 5 {集中の達人} other {ひよっこ}}から{newTierLevel, select, 1 {ひよっこ} 2 {ウォームアップ} 3 {超集中} 4 {充実ライフ} 5 {集中の達人} other {ひよっこ}}へ移動しました。今週も頑張ろう！} other {今週の目標は？さっそく集中を始めよう！}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_WEEKLY_RESULT.zh-Hant','LEAGUE_WEEKLY_RESULT','zh-Hant','{result, select, PROMOTED {🎉 我們晉級了！} RELEGATED {上週的聯賽結束了！} other {新聯賽開始了！}}','{result, select, PROMOTED {這週的專注讓你從{previousTierLevel, select, 1 {新手} 2 {暖身模式} 3 {超專注} 4 {自律達人} 5 {專注王者} other {新手}}晉級到{newTierLevel, select, 1 {新手} 2 {暖身模式} 3 {超專注} 4 {自律達人} 5 {專注王者} other {新手}}。來看看新排名！} RELEGATED {從{previousTierLevel, select, 1 {新手} 2 {暖身模式} 3 {超專注} 4 {自律達人} 5 {專注王者} other {新手}}移動到{newTierLevel, select, 1 {新手} 2 {暖身模式} 3 {超專注} 4 {自律達人} 5 {專注王者} other {新手}}。這週繼續加油！} other {這週的目標是什麼？現在就開始專注吧！}}');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('LEAGUE_WEEKLY_RESULT','{result, select, PROMOTED {gromo://league} RELEGATED {gromo://focus} other {gromo://league}}','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('LEAGUE_DEADLINE',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_DEADLINE.ko','LEAGUE_DEADLINE','ko','리그 마감까지 4시간!','지금 {rank}위야. 마지막 스퍼트 한 번 어때?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_DEADLINE.en','LEAGUE_DEADLINE','en','4 hours until the league ends!','You’re ranked #{rank}. Ready for one last push?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_DEADLINE.ja','LEAGUE_DEADLINE','ja','リーグ終了まであと4時間！','現在{rank}位だよ。最後にもうひと頑張りしよう！');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_DEADLINE.zh-Hant','LEAGUE_DEADLINE','zh-Hant','距離聯賽結束還有4小時！','你目前排名第{rank}。最後再衝刺一下吧！');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('LEAGUE_DEADLINE','gromo://league','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('LEAGUE_FINAL_DEADLINE',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_FINAL_DEADLINE.ko','LEAGUE_FINAL_DEADLINE','ko','마감 2시간 전!','지금 {rank}위야. 마지막 스퍼트 한 번 어때?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_FINAL_DEADLINE.en','LEAGUE_FINAL_DEADLINE','en','2 hours to go!','You’re ranked #{rank}. Ready for one last push?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_FINAL_DEADLINE.ja','LEAGUE_FINAL_DEADLINE','ja','終了まであと2時間！','現在{rank}位だよ。最後にもうひと頑張りしよう！');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_FINAL_DEADLINE.zh-Hant','LEAGUE_FINAL_DEADLINE','zh-Hant','距離結束還有2小時！','你目前排名第{rank}。最後再衝刺一下吧！');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('LEAGUE_FINAL_DEADLINE','gromo://focus','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('LEAGUE_DEADLINE_D1',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_DEADLINE_D1.ko','LEAGUE_DEADLINE_D1','ko','리그 마감 하루 전!','승급까지 {shortfallHours, plural, =0 {{shortfallMinutes}분} other {#시간{shortfallRemainder, plural, =0 {} other { #분}}}} 남았어. 오늘 몰아쳐볼까?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_DEADLINE_D1.en','LEAGUE_DEADLINE_D1','en','League deadline tomorrow!','Just {shortfallHours, plural, =0 {{shortfallMinutes, plural, one {# minute} other {# minutes}}} one {# hour{shortfallRemainder, plural, =0 {} one { # minute} other { # minutes}}} other {# hours{shortfallRemainder, plural, =0 {} one { # minute} other { # minutes}}}} to move up. Let’s focus today!');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_DEADLINE_D1.ja','LEAGUE_DEADLINE_D1','ja','リーグ締め切り前日！','昇格まであと{shortfallHours, plural, =0 {{shortfallMinutes}分} other {#時間{shortfallRemainder, plural, =0 {} other {#分}}}}。今日は集中しよう！');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_DEADLINE_D1.zh-Hant','LEAGUE_DEADLINE_D1','zh-Hant','聯賽截止前一天！','再專注{shortfallHours, plural, =0 {{shortfallMinutes}分鐘} other {#小時{shortfallRemainder, plural, =0 {} other {#分鐘}}}}就能晉級。今天一起努力吧！');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('LEAGUE_DEADLINE_D1','gromo://league','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('LEAGUE_RELEGATION_WARNING',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_RELEGATION_WARNING.ko','LEAGUE_RELEGATION_WARNING','ko','강등 위기야!','이번 주 {shortfallHours, plural, =0 {{shortfallMinutes}분} other {#시간{shortfallRemainder, plural, =0 {} other { #분}}}} 더 채워야 강등을 피할 수 있어. 지금 몰입할까?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_RELEGATION_WARNING.en','LEAGUE_RELEGATION_WARNING','en','Your league spot is at risk!','Focus for {shortfallHours, plural, =0 {{shortfallMinutes, plural, one {# minute} other {# minutes}}} one {# hour{shortfallRemainder, plural, =0 {} one { # minute} other { # minutes}}} other {# hours{shortfallRemainder, plural, =0 {} one { # minute} other { # minutes}}}} more this week to avoid relegation.');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_RELEGATION_WARNING.ja','LEAGUE_RELEGATION_WARNING','ja','降格のピンチ！','今週あと{shortfallHours, plural, =0 {{shortfallMinutes}分} other {#時間{shortfallRemainder, plural, =0 {} other {#分}}}}集中すれば降格を避けられるよ。');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_RELEGATION_WARNING.zh-Hant','LEAGUE_RELEGATION_WARNING','zh-Hant','有降級的危險！','這週再專注{shortfallHours, plural, =0 {{shortfallMinutes}分鐘} other {#小時{shortfallRemainder, plural, =0 {} other {#分鐘}}}}就能避免降級。');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('LEAGUE_RELEGATION_WARNING','gromo://focus','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('LEAGUE_RELEGATION_WARNING_EVENING',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_RELEGATION_WARNING_EVENING.ko','LEAGUE_RELEGATION_WARNING_EVENING','ko','강등 위기야!','이번 주 {shortfallHours, plural, =0 {{shortfallMinutes}분} other {#시간{shortfallRemainder, plural, =0 {} other { #분}}}} 더 채워야 강등을 피할 수 있어. 지금 몰입할까?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_RELEGATION_WARNING_EVENING.en','LEAGUE_RELEGATION_WARNING_EVENING','en','Your league spot is at risk!','Focus for {shortfallHours, plural, =0 {{shortfallMinutes, plural, one {# minute} other {# minutes}}} one {# hour{shortfallRemainder, plural, =0 {} one { # minute} other { # minutes}}} other {# hours{shortfallRemainder, plural, =0 {} one { # minute} other { # minutes}}}} more this week to avoid relegation.');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_RELEGATION_WARNING_EVENING.ja','LEAGUE_RELEGATION_WARNING_EVENING','ja','降格のピンチ！','今週あと{shortfallHours, plural, =0 {{shortfallMinutes}分} other {#時間{shortfallRemainder, plural, =0 {} other {#分}}}}集中すれば降格を避けられるよ。');
INSERT INTO templates(id,kind,locale,title,body) VALUES('LEAGUE_RELEGATION_WARNING_EVENING.zh-Hant','LEAGUE_RELEGATION_WARNING_EVENING','zh-Hant','有降級的危險！','這週再專注{shortfallHours, plural, =0 {{shortfallMinutes}分鐘} other {#小時{shortfallRemainder, plural, =0 {} other {#分鐘}}}}就能避免降級。');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('LEAGUE_RELEGATION_WARNING_EVENING','gromo://focus','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('INACTIVE_RETURN',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('INACTIVE_RETURN.ko','INACTIVE_RETURN','ko','{stage, select, D3 {요즘 안 보이네} D7 {벌써 일주일째야} other {처음 그 마음, 기억나?}}','{stage, select, D3 {방이 좀 허전해. 잠깐 들러서 얼굴만 보여줄래?} D7 {네가 모은 코인이랑 방, 그대로 기다리고 있어. 5분만 같이 집중할까?} other {네가 직접 정한 목표가 아직 그대로 남아있어. 초심으로 딱 한 번만 다시 시작해보자.}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('INACTIVE_RETURN.en','INACTIVE_RETURN','en','{stage, select, D3 {We haven’t seen you lately} D7 {It’s been a week} other {Remember why you started?}}','{stage, select, D3 {Your room feels empty. Drop by for a moment?} D7 {Your coins and room are waiting. Focus together for 5 minutes?} other {Your goal is still here. Take one small step toward it today.}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('INACTIVE_RETURN.ja','INACTIVE_RETURN','ja','{stage, select, D3 {最近見かけないね} D7 {もう1週間だね} other {始めたときの気持ち、覚えてる？}}','{stage, select, D3 {部屋がちょっと寂しいよ。少しだけ顔を見せてくれる？} D7 {コインも部屋も待っているよ。5分だけ一緒に集中しよう！} other {自分で決めた目標はそのままだよ。もう一度、一歩踏み出してみよう。}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('INACTIVE_RETURN.zh-Hant','INACTIVE_RETURN','zh-Hant','{stage, select, D3 {最近沒看到你呢} D7 {已經一週了} other {還記得最初的心情嗎？}}','{stage, select, D3 {房間有點冷清。回來打個招呼好嗎？} D7 {你的金幣和房間都在等你。一起專注5分鐘吧！} other {你訂下的目標還在。今天再踏出一小步吧。}}');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('INACTIVE_RETURN','gromo://home','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('MISSED_FOCUS_TODAY',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('MISSED_FOCUS_TODAY.ko','MISSED_FOCUS_TODAY','ko','오늘 아직 0분!','지금 순위 밀리는 중이야. 딱 10분만 몰입해볼까?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('MISSED_FOCUS_TODAY.en','MISSED_FOCUS_TODAY','en','No focus time yet today!','Your rank is slipping. How about just 10 minutes?');
INSERT INTO templates(id,kind,locale,title,body) VALUES('MISSED_FOCUS_TODAY.ja','MISSED_FOCUS_TODAY','ja','今日はまだ0分！','順位が下がっているよ。10分だけ集中しよう！');
INSERT INTO templates(id,kind,locale,title,body) VALUES('MISSED_FOCUS_TODAY.zh-Hant','MISSED_FOCUS_TODAY','zh-Hant','今天還是0分鐘！','排名正在下滑。先專注10分鐘吧！');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('MISSED_FOCUS_TODAY','gromo://focus','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('STREAK_AT_RISK',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('STREAK_AT_RISK.ko','STREAK_AT_RISK','ko','출석 {streakCount}일 끊기기 직전!','10분만 채우면 연속 출석 유지! 지금 시작하자');
INSERT INTO templates(id,kind,locale,title,body) VALUES('STREAK_AT_RISK.en','STREAK_AT_RISK','en','Your {streakCount}-day streak is at risk!','Focus for 10 minutes to keep your streak going!');
INSERT INTO templates(id,kind,locale,title,body) VALUES('STREAK_AT_RISK.ja','STREAK_AT_RISK','ja','{streakCount}日連続の記録が途切れそう！','10分集中すれば記録を維持できるよ！');
INSERT INTO templates(id,kind,locale,title,body) VALUES('STREAK_AT_RISK.zh-Hant','STREAK_AT_RISK','zh-Hant','連續{streakCount}天的紀錄快中斷了！','專注10分鐘就能延續紀錄。現在開始吧！');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('STREAK_AT_RISK','gromo://focus','{}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('BET_RESULT',false,'DEFER',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_RESULT.ko','BET_RESULT','ko','내기 결과가 나왔어요','{betOutcome, select, FORFEITED {아무도 목표를 달성하지 못해 참가비가 소멸됐어요} WON {내기에서 이겼어요! +{payout}코인 🎉} other {아쉬워요 — 목표 미달성으로 참가비 {stake}코인을 잃었어요}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_RESULT.en','BET_RESULT','en','Your bet result is here','{betOutcome, select, FORFEITED {Nobody reached the goal, so the entry fees were forfeited} WON {You won! +{payout} coins 🎉} other {You missed the goal and lost your {stake}-coin entry fee}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_RESULT.ja','BET_RESULT','ja','ベットの結果が出ました','{betOutcome, select, FORFEITED {誰も目標を達成できず、参加費は没収されました} WON {勝利！+{payout}コイン 🎉} other {目標未達成で参加費{stake}コインを失いました}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_RESULT.zh-Hant','BET_RESULT','zh-Hant','挑戰結果出爐了','{betOutcome, select, FORFEITED {沒有人達成目標，因此報名費已被沒收} WON {你贏了！+{payout}金幣 🎉} other {未達成目標，失去了{stake}金幣報名費}}');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('BET_RESULT','gromo://group?g={groupId}','{"type":"BET_RESULT"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('BET_VOID_REFUND',false,'DEFER',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_VOID_REFUND.ko','BET_VOID_REFUND','ko','참가비를 돌려드렸어요','{voidReason, select, CHALLENGE_DELETED {챌린지가 삭제돼 무산됐어요 · 참가비는 돌려드렸어요} INSUFFICIENT_PARTICIPANTS {참가자가 부족해 무산됐어요 · 참가비는 돌려드렸어요} REFUND_DEADLINE {정산이 지연돼 참가비를 돌려드렸어요} other {내기가 무산돼 참가비를 돌려드렸어요}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_VOID_REFUND.en','BET_VOID_REFUND','en','Your entry fee was refunded','{voidReason, select, CHALLENGE_DELETED {The challenge was deleted, so your entry fee was refunded} INSUFFICIENT_PARTICIPANTS {There were too few participants, so your entry fee was refunded} REFUND_DEADLINE {Settlement was delayed, so your entry fee was refunded} other {The bet was cancelled and your entry fee was refunded}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_VOID_REFUND.ja','BET_VOID_REFUND','ja','参加費を返金しました','{voidReason, select, CHALLENGE_DELETED {チャレンジが削除されたため、参加費を返金しました} INSUFFICIENT_PARTICIPANTS {参加者が不足したため、参加費を返金しました} REFUND_DEADLINE {精算が遅れたため、参加費を返金しました} other {ベットが中止となり、参加費を返金しました}}');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_VOID_REFUND.zh-Hant','BET_VOID_REFUND','zh-Hant','報名費已退還','{voidReason, select, CHALLENGE_DELETED {挑戰已刪除，因此退還報名費} INSUFFICIENT_PARTICIPANTS {參加人數不足，因此退還報名費} REFUND_DEADLINE {結算延遲，因此退還報名費} other {挑戰取消，報名費已退還}}');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('BET_VOID_REFUND',NULL,'{"type":"BET_VOID_REFUND"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('BET_WON',false,'DROP',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_WON.ko','BET_WON','ko','목표 달성! 🎉','승리가 확정됐어요 — 정산되면 적립금이 들어와요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_WON.en','BET_WON','en','Goal reached! 🎉','Your win is confirmed. Your reward arrives after settlement.');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_WON.ja','BET_WON','ja','目標達成！🎉','勝利が確定しました。精算後に報酬が入ります。');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_WON.zh-Hant','BET_WON','zh-Hant','目標達成！🎉','勝利已確定，結算後會收到獎勵。');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('BET_WON',NULL,'{"type":"BET_WON"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('BET_SILENT_FLUSH',true,'BYPASS',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_SILENT_FLUSH.ko','BET_SILENT_FLUSH','ko',NULL,'');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_SILENT_FLUSH.en','BET_SILENT_FLUSH','en',NULL,'');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_SILENT_FLUSH.ja','BET_SILENT_FLUSH','ja',NULL,'');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_SILENT_FLUSH.zh-Hant','BET_SILENT_FLUSH','zh-Hant',NULL,'');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('BET_SILENT_FLUSH',NULL,'{"silent":"flush"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('CHALLENGE_SESSION_OPEN',false,'DEFER',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_SESSION_OPEN.ko','CHALLENGE_SESSION_OPEN','ko','오늘 참여할 챌린지가 있어요','참가비 {stake}코인 — 지금 참여할 수 있어요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_SESSION_OPEN.en','CHALLENGE_SESSION_OPEN','en','A challenge is open today','Entry costs {stake} coins. You can join now!');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_SESSION_OPEN.ja','CHALLENGE_SESSION_OPEN','ja','今日参加できるチャレンジがあります','参加費は{stake}コイン。今すぐ参加できます！');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_SESSION_OPEN.zh-Hant','CHALLENGE_SESSION_OPEN','zh-Hant','今天有可以參加的挑戰','報名費{stake}金幣。現在就能參加！');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('CHALLENGE_SESSION_OPEN',NULL,'{"type":"CHALLENGE_SESSION_OPEN"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('CHALLENGE_WINDOW_END',false,'DROP',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_WINDOW_END.ko','CHALLENGE_WINDOW_END','ko','챌린지가 끝났어요!','결과를 확인해보세요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_WINDOW_END.en','CHALLENGE_WINDOW_END','en','The challenge is over!','Check your results');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_WINDOW_END.ja','CHALLENGE_WINDOW_END','ja','チャレンジが終了しました！','結果を確認しましょう');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_WINDOW_END.zh-Hant','CHALLENGE_WINDOW_END','zh-Hant','挑戰結束了！','來確認結果吧');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('CHALLENGE_WINDOW_END','gromo://group?g={groupId}&challenge={challengeId}','{"type":"CHALLENGE_WINDOW_END"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('CHALLENGE_ENDED',false,'DROP',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_ENDED.ko','CHALLENGE_ENDED','ko','챌린지가 끝났어요!','어제 목표 달성 결과를 확인해보세요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_ENDED.en','CHALLENGE_ENDED','en','The challenge is over!','See how you did on yesterday’s goal');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_ENDED.ja','CHALLENGE_ENDED','ja','チャレンジが終了しました！','昨日の目標の達成結果を確認しましょう');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_ENDED.zh-Hant','CHALLENGE_ENDED','zh-Hant','挑戰結束了！','來看看昨天的目標達成結果');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('CHALLENGE_ENDED','gromo://group?g={groupId}&challenge={challengeId}','{"type":"CHALLENGE_ENDED"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('CHALLENGE_CREATED',false,'DROP',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_CREATED.ko','CHALLENGE_CREATED','ko','{groupName}에 새 챌린지가 열렸어요','{missionLabel} — 지금 참여해보세요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_CREATED.en','CHALLENGE_CREATED','en','A new challenge in {groupName}','{missionLabel} — join now!');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_CREATED.ja','CHALLENGE_CREATED','ja','{groupName}に新しいチャレンジ','{missionLabel} — 今すぐ参加しよう！');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_CREATED.zh-Hant','CHALLENGE_CREATED','zh-Hant','{groupName}有新挑戰','{missionLabel} — 現在就參加吧！');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('CHALLENGE_CREATED','gromo://group?g={groupId}','{"type":"CHALLENGE_CREATED"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('FRIEND_REQUEST',false,'DROP',true);
INSERT INTO templates(id,kind,locale,title,body) VALUES('FRIEND_REQUEST.ko','FRIEND_REQUEST','ko','새로운 친구 요청','{counterpartNickname}님이 친구 요청을 보냈어요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('FRIEND_REQUEST.en','FRIEND_REQUEST','en','New friend request','{counterpartNickname} sent you a friend request');
INSERT INTO templates(id,kind,locale,title,body) VALUES('FRIEND_REQUEST.ja','FRIEND_REQUEST','ja','新しいフレンド申請','{counterpartNickname}さんからフレンド申請が届きました');
INSERT INTO templates(id,kind,locale,title,body) VALUES('FRIEND_REQUEST.zh-Hant','FRIEND_REQUEST','zh-Hant','新的好友邀請','{counterpartNickname}向你發送了好友邀請');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('FRIEND_REQUEST','gromo://friends','{"type":"FRIEND_REQUEST"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('FRIEND_ACCEPTED',false,'DROP',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('FRIEND_ACCEPTED.ko','FRIEND_ACCEPTED','ko','친구가 됐어요!','{counterpartNickname}님이 친구 요청을 수락했어요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('FRIEND_ACCEPTED.en','FRIEND_ACCEPTED','en','You’re now friends!','{counterpartNickname} accepted your friend request');
INSERT INTO templates(id,kind,locale,title,body) VALUES('FRIEND_ACCEPTED.ja','FRIEND_ACCEPTED','ja','フレンドになりました！','{counterpartNickname}さんがフレンド申請を承認しました');
INSERT INTO templates(id,kind,locale,title,body) VALUES('FRIEND_ACCEPTED.zh-Hant','FRIEND_ACCEPTED','zh-Hant','成為好友了！','{counterpartNickname}接受了你的好友邀請');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('FRIEND_ACCEPTED','gromo://friends','{"type":"FRIEND_ACCEPTED"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('BET_RESULT_BUNDLE',false,'DEFER',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_RESULT_BUNDLE.ko','BET_RESULT_BUNDLE','ko','내기 결과가 나왔어요','내기 결과 {resultCount}건이 나왔어요 — 그룹에서 확인하세요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_RESULT_BUNDLE.en','BET_RESULT_BUNDLE','en','Your bet results are here','{resultCount} bet results are ready. Check your group!');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_RESULT_BUNDLE.ja','BET_RESULT_BUNDLE','ja','ベットの結果が出ました','{resultCount}件の結果をグループで確認しましょう');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_RESULT_BUNDLE.zh-Hant','BET_RESULT_BUNDLE','zh-Hant','挑戰結果出爐了','有{resultCount}筆結果，請到群組查看');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('BET_RESULT_BUNDLE','gromo://group?g={groupId}','{"type":"BET_RESULT"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('BET_VOID_REFUND_BUNDLE',false,'DEFER',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_VOID_REFUND_BUNDLE.ko','BET_VOID_REFUND_BUNDLE','ko','참가비를 돌려드렸어요','내기 {refundCount}건이 무산돼 참가비를 돌려드렸어요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_VOID_REFUND_BUNDLE.en','BET_VOID_REFUND_BUNDLE','en','Your entry fees were refunded','{refundCount} bets were cancelled and their entry fees refunded');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_VOID_REFUND_BUNDLE.ja','BET_VOID_REFUND_BUNDLE','ja','参加費を返金しました','{refundCount}件のベットが中止となり、参加費を返金しました');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_VOID_REFUND_BUNDLE.zh-Hant','BET_VOID_REFUND_BUNDLE','zh-Hant','報名費已退還','{refundCount}場挑戰取消，報名費已退還');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('BET_VOID_REFUND_BUNDLE',NULL,'{"type":"BET_VOID_REFUND"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('BET_MIXED_BUNDLE',false,'DEFER',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_MIXED_BUNDLE.ko','BET_MIXED_BUNDLE','ko','내기 소식이 도착했어요','결과 {resultCount}건 · 무산 환불 {refundCount}건 — 그룹에서 확인하세요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_MIXED_BUNDLE.en','BET_MIXED_BUNDLE','en','News about your bets','{resultCount} results · {refundCount} refunds. Check your group!');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_MIXED_BUNDLE.ja','BET_MIXED_BUNDLE','ja','ベットのお知らせ','結果{resultCount}件・返金{refundCount}件。グループで確認しましょう');
INSERT INTO templates(id,kind,locale,title,body) VALUES('BET_MIXED_BUNDLE.zh-Hant','BET_MIXED_BUNDLE','zh-Hant','挑戰有新消息','{resultCount}筆結果・{refundCount}筆退款，請到群組查看');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('BET_MIXED_BUNDLE','gromo://group?g={groupId}','{"type":"BET_RESULT"}'::jsonb);
INSERT INTO kinds(id,silent,quiet_policy,eligibility_required) VALUES('CHALLENGE_SESSION_OPEN_BUNDLE',false,'DEFER',false);
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_SESSION_OPEN_BUNDLE.ko','CHALLENGE_SESSION_OPEN_BUNDLE','ko','오늘 참여할 챌린지가 있어요','참여 가능한 챌린지 {count}개가 열려 있어요');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_SESSION_OPEN_BUNDLE.en','CHALLENGE_SESSION_OPEN_BUNDLE','en','Challenges are open today','{count} challenges are available to join');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_SESSION_OPEN_BUNDLE.ja','CHALLENGE_SESSION_OPEN_BUNDLE','ja','今日参加できるチャレンジがあります','参加可能なチャレンジが{count}件あります');
INSERT INTO templates(id,kind,locale,title,body) VALUES('CHALLENGE_SESSION_OPEN_BUNDLE.zh-Hant','CHALLENGE_SESSION_OPEN_BUNDLE','zh-Hant','今天有可以參加的挑戰','有{count}個挑戰開放參加');
INSERT INTO deeplinks(id,url_template,data_template) VALUES('CHALLENGE_SESSION_OPEN_BUNDLE',NULL,'{"type":"CHALLENGE_SESSION_OPEN"}'::jsonb);
