#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — dev Notification Kafka cutover
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="${ENV_FILE:-doc/dev-notification-cutover.env}"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "$1 명령이 필요합니다."
    exit 1
  fi
}

dispatch_and_wait() {
  local workflow="$1" action="$2" previous run_id=""
  previous=$(gh run list --workflow "$workflow" --limit 1 --json databaseId --jq '.[0].databaseId // ""')
  gh workflow run "$workflow" -f "action=$action"
  for _ in $(seq 1 30); do
    run_id=$(gh run list --workflow "$workflow" --event workflow_dispatch --limit 1 \
      --json databaseId --jq '.[0].databaseId // ""')
    if [[ -n "$run_id" && "$run_id" != "$previous" ]]; then
      gh run watch "$run_id" --exit-status
      return
    fi
    sleep 2
  done
  warn "$workflow의 새 실행을 60초 안에 찾지 못했습니다."
  exit 1
}

banner "Dev Notification Kafka cutover"

stage "도구와 현재 상태 확인"
say "이 wizard는 dev만 대상으로 하며 OUTBOX 전환은 단방향입니다."
require_command gh
require_command aws
require_command jq
gh auth status
step "AWS CLI가 romance dev 계정의 Secrets Manager를 읽을 수 있는지 확인합니다."
aws secretsmanager describe-secret --secret-id gromo/dev/env --region ap-northeast-2 >/dev/null
step "현재 열려 있는 배포 PR과 Actions 실행이 없음을 확인하세요."
open_url "https://github.com/OneOrThree/phone/actions"
confirm "동시에 실행 중인 dev 배포가 없습니까?" || exit 1

stage "Kafka 브로커 기동"
say "Dev Kafka workflow가 메모리 1024 MiB 게이트를 검사하고 broker만 기동합니다."
dispatch_and_wait dev-kafka.yml up
step "실행 요약에서 broker health=healthy를 확인하세요."
confirm "Kafka가 healthy입니까?" || exit 1

stage "Relay 정책 기록"
say "승인된 dev relay 정책을 로컬 실행 기록에 보존합니다."
write_env OUTBOX_RELAY_BATCH_SIZE "100"
write_env OUTBOX_RELAY_LEASE_DURATION "30s"
write_env OUTBOX_RELAY_POLL_INTERVAL "1s"
write_env OUTBOX_RELAY_INITIAL_BACKOFF "1s"
write_env OUTBOX_RELAY_MAX_BACKOFF "1m"
write_env OUTBOX_RELAY_WARNING_ATTEMPTS "10"
chmod 600 "$ENV_FILE"
note "이 파일은 doc/ 아래라 git에 커밋되지 않습니다."

stage "Secrets Manager 준비"
say "AWS Console에서 gromo/dev/env JSON에 relay 값 6개를 추가합니다."
open_url "https://ap-northeast-2.console.aws.amazon.com/secretsmanager/secret?name=gromo%2Fdev%2Fenv&region=ap-northeast-2"
step "위 6개 값을 입력하되 OUTBOX_RELAY_ENABLED=false, NOTIFICATION_DISPATCH_MODE=LEGACY를 유지하세요."
step "KAFKA_BOOTSTRAP_SERVERS=kafka:9092와 기존 REALTIME_BASE_URL/SVC_TOKEN_DATA_TO_REALTIME가 비어 있지 않은지 확인하세요."
confirm "시크릿 저장을 마쳤습니까?" || exit 1

stage "Notification 수신기 준비"
say "Notification은 먼저 Kafka를 소비해 DB에 내구 적재하되 최종 발송 gate는 닫힌 상태여야 합니다."
step "gromo/dev/env에서 NOTIFICATION_KAFKA_ENABLED=true를 설정하세요."
step "NOTIFICATION_SCHEDULING_ENABLED=false와 dispatch_control.enabled=false를 유지하세요."
step "Notification을 재배포한 뒤 /health가 정상인지 확인하세요."
confirm "Notification 수신기가 healthy이고 발송 gate는 닫혀 있습니까?" || exit 1

stage "DLT와 토픽 준비·검증"
say "원본 토픽과 DLT는 파티션 수가 같아야 원본 파티션의 실패 사건을 보존합니다."
dispatch_and_wait dev-kafka.yml prepare
step "실행 로그에서 notification-events와 notification-events.DLT가 각각 3 partitions인지 확인하세요."
step "consumer group notification-v1의 lag와 DLT 적재 건수가 0인지 확인하세요."
confirm "토픽 2개가 3 partitions이고 DLT/lag가 0입니까?" || exit 1

stage "Relay 활성화와 drain"
warn "이 단계부터 Data outbox가 Kafka로 실제 발행됩니다."
confirm "relay를 켜고 backlog drain을 시작할까요?" || exit 1
step "gromo/dev/env에서 OUTBOX_RELAY_ENABLED=true로 바꾸고 Data API를 재배포하세요."
step "event_outbox_delivery의 KAFKA 미전달 건수, notification-v1 lag, notification-events.DLT가 모두 0이 될 때까지 기다리세요."
confirm "미전달·lag·DLT가 모두 0입니까?" || exit 1

stage "OUTBOX 단방향 전환"
warn "OUTBOX에서 LEGACY로 설정만 되돌리면 이미 발송된 알림이 중복될 수 있습니다."
confirm "최종 단방향 전환을 수행할까요?" || exit 1
step "gromo/dev/env에서 NOTIFICATION_DISPATCH_MODE=OUTBOX로 바꾸고 Data API를 재배포하세요."
step "친구 요청/수락, 챌린지 개설, 내기 승리, 회차 종료 사건을 각각 1회 발생시키세요."
step "Datadog에서 Data producer → Kafka → Notification consumer trace와 service 태그를 확인하세요."
step "notification-events.DLT=0, consumer lag=0, 중복 발송=0을 확인하세요."
confirm "5개 사건의 end-to-end 검증을 마쳤습니까?" || exit 1

finish
