name: TestFlight 배포

on:
  push:
    branches:
      - main
    # app/ 디렉터리 하위의 파일이 변경되었을 때만 자동 실행
    paths:
      - 'app/**'
  
  # 수동 실행 기능 유지
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, spot]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Expo 패키지 설치
        run: npm install -g eas-cli

      - name: 의존성 설치
        working-directory: app
        run: npm install

      - name: EAS 빌드 & TestFlight 제출
        working-directory: app
        run: eas build --platform ios --profile production --auto-submit --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
